project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: "HIM in R"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Physician Fee Schedule"
        file: pfs.qmd
      - text: "EDI Payer List"
        file: payer_list.qmd
      - text: "Taxonomy"
        file: taxonomy.qmd
  
sidebar:
  - title: "Physician Fee Schedule"
    style: "docked"
    background: light
    contents:
       - pfs.qmd
       - calculation.qmd
      
  - title: "EDI Payer List"
    contents:
      - payer_list.qmd
    
  - title: "Taxonomy"
    contents:
      - taxonomy.qmd

format:
  html:
    theme:
      - zephyr
      - styles.scss
    date: last-modified
    fontsize: 16px
    linestretch: 1.75
    code-link: true
    code-fold: false
    code-tools: true
    embed-resources: false
    toc: true

editor: visual

execute:
  freeze: auto
  collapse: true
  echo: true
  cache: true

published-title: "Last updated"
number-depth: 2
fig-width: 8
fig-height: 5
fig-align: center
output-width: 100%
highlight-style: tango
site-url: https://andrewallenbruce.github.io/himnr/
repo-url: https://github.com/andrewallenbruce/himnr
  