project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
filters:
  - acronyms
acronyms:
  loa_title: "Glossary"
  loa_header_classes: []
  include_unused: false
  insert_loa: "end"
  insert_links: true
  id_prefix: "acronyms_"
  sorting: "alphabetical"
  non_existing: "key"
  style: "short-footnote"
  fromfile: acronyms.yml

website:
  title: "HIM in R"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pfs.qmd
        text: Physician Fee Schedule
      - href: payer_list.qmd
        text: EDI Payer List
      - href: taxonomy.qmd
        text: Taxonomy
      - about.qmd
  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme:
      - zephyr
      - styles.scss
    date: last-modified
    fontsize: 16px
    linestretch: 1.75
    code-link: true
    code-fold: false
    code-tools: true
    embed-resources: false
    toc: true

editor: visual

execute:
  freeze: auto
  collapse: true
  echo: true
  cache: true

page-footer:
    left: "Built with [Quarto](https://quarto.org). {{< fa copyright >}} [Andrew Bruce](andrew.bruce@northstarrevenueintegrity.com)"
    border: false
    background: light

published-title: "Last updated"
number-depth: 2
fig-width: 8
fig-height: 5
fig-align: center
output-width: 100%
highlight-style: tango
site-url: https://andrewallenbruce.github.io/himnr/
repo-url: https://github.com/andrewallenbruce/himnr
  