project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: "HIM in R"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: pfs.qmd
        text: Physician Fee Schedule
      - href: payer_list.qmd
        text: EDI Payer List
      - href: taxonomy.qmd
        text: Taxonomy
      - about.qmd
  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme:
      - zephyr
      - styles.scss
    date: last-modified
    fontsize: 18px
    linestretch: 1.5
    code-link: true
    code-fold: false
    code-tools: true
    code-block-bg: true
    embed-resources: false
    toc: true

editor: visual

execute:
  freeze: auto
  collapse: true
  echo: true
  cache: true